#!/usr/bin/env python3
"""
build.py - Build Langrisser III English Translation Patch

Single-command build pipeline that:
1. Reads the Japanese disc image
2. Extracts FONT.BIN and D00.DAT
3. Generates English font from JP FONT.BIN + embedded glyph data
4. Encodes English translation scripts into D00.DAT
5. Rebuilds ISO with larger D00.DAT (sector-shifting)
6. Assembles final CD image with audio tracks

Usage:
    python3 build.py

Requires:
    - Japanese disc image at the configured JP_DIR path
    - English translation scripts in scripts/en/

Output (a self-contained folder named after the .cue):
    build/Langrisser III (English v0.6+new-ui-patch)/
        Langrisser III (English v0.6+new-ui-patch).cue  (load this in emulator)
        track01.bin ... track22.bin
"""

import os
import shutil
import sys
import time
from pathlib import Path

# Add tools directory to path
SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR / 'tools'))

from iso_tools import (
    build_file_index, extract_file_data, patch_file_in_iso,
    rebuild_iso_inorder, rebuild_iso_batch, assemble_cd_image, SECTOR_SIZE
)
from d00_tools import (
    parse_d00, insert_translations, rebuild_d00
)
from font_tools import (
    CHAR_TILE_MAP, BIGRAM_TILE_MAP, generate_english_font,
)
from plot_tools import (
    encode_plot_script, parse_plot, round_trip_test as plot_round_trip,
)
from fnt_sys_tools import encode_fntsys
from syswin_tools import encode_syswin
from byte_overlays import BYTE_OVERLAYS

# The data-driven font is now the production default (font_tools Part 6 swap,
# 2026-06-26): BIGRAM_TILE_MAP / generate_english_font ARE the packed in-place
# layout, the rigorous trailing-(c,space) rule applies to all surfaces, and the
# fntsys map is gap-filled from the layout (kills the OPTIONS/RAM/PCM zenkaku
# fallback). Validated by the LANG3_NEW_FONT=1 playtest before the swap.
import new_encoder as _new_encoder
import d00_tools as _d00_tools
_d00_tools.TRAILING_BIGRAM_DEFAULT = True
_D00_BIGRAM = BIGRAM_TILE_MAP
_FNTSYS_OVERRIDE = _new_encoder.relocated_fntsys_bigram_map()
from prog_text_tools import encoded_overlays as prog_text_encoded_overlays
from prog3_nameplate_new_line import PROG3_NAMEPLATE_NEW_LINE
from prog3_statup_template import PROG3_STATUP_TEMPLATE
from prog4_field_box_geometry import PROG4_FIELD_BOX_GEOMETRY
from prog4_equip_title import PROG4_EQUIP_TITLE
from a0lang_options_menu_geometry import A0LANG_OPTIONS_MENU_GEOMETRY
from a0lang_title_menu_geometry import A0LANG_TITLE_MENU_GEOMETRY
from a0lang_loadsave_title import A0LANG_LOADSAVE_TITLE
from a0lang_item_action_box import A0LANG_ITEM_ACTION_BOX
from prog3_item_use_glue import PROG3_ITEM_USE_GLUE
from prog6_battle_cmd_width import PROG6_BATTLE_CMD_WIDTH
from prog4_spell_name_table import PROG4_SPELL_NAME_TABLE
from prog5_menu_geometry import PROG5_MENU_GEOMETRY
from prog4_menu_geometry import PROG4_MENU_GEOMETRY
from patch_registry import is_enabled, disabled_modules, validate as validate_disabled
import title_dg2

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

BUILD_DIR = SCRIPT_DIR / 'build'
CACHE_DIR = SCRIPT_DIR / 'cache'   # JP baseline cache (gitignored)
PATCHES_DIR = SCRIPT_DIR / 'patches'  # Menu/UI translation patches

# Opening FMV (LANG/LANG.CPK). The encoded, English-subtitled CPK is a large
# (~21 MB) binary asset kept OUT of git (the repo holds no LFS and no file this
# big); it is regenerated by tools/movie_tools.py from the external upscaled
# source + the committed assets/movie/opening_en.srt. If the asset is absent,
# the build ships the JP opening unchanged. Override the path with
# LANG3_MOVIE_CPK for a one-off build.
MOVIE_DIR = SCRIPT_DIR / 'assets' / 'movie'
MOVIE_CPK = Path(os.environ.get('LANG3_MOVIE_CPK', MOVIE_DIR / 'LANG.CPK'))

# Title-screen credit. assets/title_credit/title_credit_indexed.png is an indexed
# (mode 'P') canvas whose footer rows carry the patch-author credit; the build
# tiles them into LANG/TITLE.DG2 (tools/title_dg2.py). Absent -> JP title.
TITLE_CREDIT_ASSET = SCRIPT_DIR / 'assets' / 'title_credit' / 'title_credit_indexed.png'

# Language metadata. The repo is dual-purpose: an English translation patch
# AND a framework for producing Langrisser III patches in any language.
# Each language has its own scripts/<code>/ directory and a display name
# used in the output filename.
LANGUAGES = {
    'en': 'English',
    # Add new languages here as their scripts/<code>/ dirs come online.
    # 'it': 'Italian',
    # 'pt': 'Portuguese',
    # 'es': 'Spanish',
}
DEFAULT_LANG = 'en'

# Output naming — ONE rule, fully derived from git state (no flags):
#   HEAD exactly at the latest tag → "Langrisser III ({lang} v<TAG>).cue"
#     (clean release name; to reproduce: git checkout v0.6 && python3 build.py)
#   anything else → "Langrisser III ({lang} v<TAG>+<branch>).cue"
#     ('+' = work past the release; the branch says WHICH work — e.g.
#     "v0.6+new-ui-patch". Detached HEAD → "v0.6+detached".)
# If git is unavailable (release source archive), the stamped VERSION
# artifact gives the clean name; with neither, the bare language name.
def _git_branch() -> str:
    import subprocess
    try:
        branch = subprocess.check_output(
            ['git', 'rev-parse', '--abbrev-ref', 'HEAD'],
            cwd=str(SCRIPT_DIR), stderr=subprocess.DEVNULL,
        ).decode().strip()
        return 'detached' if branch == 'HEAD' else branch
    except Exception:
        return 'unknown'


def _read_version_artifact() -> str | None:
    """Return the version string stamped in the tracked VERSION file, or None.

    VERSION is the release artifact (written by tools/stamp_version.py at
    release time) that carries the version into builds with no `.git` —
    e.g. a GitHub source archive, where `git describe` cannot run.
    """
    try:
        ver = (SCRIPT_DIR / 'VERSION').read_text(encoding='utf-8').strip().lstrip('v')
        return ver or None
    except Exception:
        return None


def _resolve_canonical_cue_name(lang_display: str) -> str:
    """Derive a clean release filename from git state, then the VERSION artifact.

    If HEAD == latest tag → "Langrisser III ({lang} v<TAG>).cue".
    Else → "Langrisser III ({lang} v<TAG>+<branch>).cue" — '+' marks work
    past the release, the branch names which line of work.
    If git is unavailable (e.g. a release source archive with no `.git`),
    fall back to the stamped VERSION file →
        "Langrisser III ({lang} v<VERSION>).cue".
    If neither git nor VERSION resolves → "Langrisser III ({lang}).cue".
    """
    import subprocess
    try:
        latest_tag = subprocess.check_output(
            ['git', 'describe', '--tags', '--abbrev=0'],
            cwd=str(SCRIPT_DIR), stderr=subprocess.DEVNULL,
        ).decode().strip()
        head_tag = subprocess.check_output(
            ['git', 'tag', '--points-at', 'HEAD'],
            cwd=str(SCRIPT_DIR), stderr=subprocess.DEVNULL,
        ).decode().strip().splitlines()
        ver = latest_tag.lstrip('v')
        if latest_tag in head_tag:
            return f'Langrisser III ({lang_display} v{ver}).cue'
        # Work past the release: "+<branch>" names exactly which line of
        # work produced this build (e.g. "v0.6+new-ui-patch").
        return f'Langrisser III ({lang_display} v{ver}+{_git_branch()}).cue'
    except Exception:
        pass
    # git unavailable — use the release-stamped VERSION artifact.
    ver = _read_version_artifact()
    if ver:
        return f'Langrisser III ({lang_display} v{ver}).cue'
    return f'Langrisser III ({lang_display}).cue'

# Menu/UI patch files (same-size overlays onto JP originals).
# All historical 0.2 patch binaries were disembarked during Phase 2-3a of the
# new-ui-patch branch:
#   - LANG/FNT_SYS.BIN   regenerated via fnt_sys_tools.encode_fntsys
#   - A0LANG.BIN         JP verbatim (no overlay needed)
#   - LANG/PROG_3.BIN, PROG_4.BIN, PROG_5.BIN, PROG_6.BIN,
#     LANG/BATTLE/SYSWIN.BIN  →  BYTE_OVERLAYS (tools/byte_overlays.py)
# 0.2 patch baselines preserved in archive/v02_baseline/ for forensic comparison.
MENU_PATCHES = {}

# BYTE_OVERLAYS imported from tools/byte_overlays.py — see that file for
# per-binary documentation. build.py extracts JP binaries from the ISO,
# applies the (offset, bytes_chunk) edits, and patches the result back.

# Engine byte-patch modules by feature-toggle NAME (tools/patch_registry.py).
# Order matters only if two modules touched the same offset (they don't — see
# tests/test_build_module_toggle.py); kept in the historical apply order so a
# full-enabled build stays byte-identical. To disable any of these for a build,
# add its name to patch_registry.DISABLED_MODULES (or LANG3_DISABLE=...).
ENGINE_MODULE_DICTS = {
    "prog3_nameplate_new_line": PROG3_NAMEPLATE_NEW_LINE,
    "prog3_statup_template": PROG3_STATUP_TEMPLATE,
    "prog4_field_box_geometry": PROG4_FIELD_BOX_GEOMETRY,
    "prog4_equip_title": PROG4_EQUIP_TITLE,
    "a0lang_options_menu_geometry": A0LANG_OPTIONS_MENU_GEOMETRY,
    "a0lang_title_menu_geometry": A0LANG_TITLE_MENU_GEOMETRY,
    "a0lang_loadsave_title": A0LANG_LOADSAVE_TITLE,
    "a0lang_item_action_box": A0LANG_ITEM_ACTION_BOX,
    "prog3_item_use_glue": PROG3_ITEM_USE_GLUE,
    "prog6_battle_cmd_width": PROG6_BATTLE_CMD_WIDTH,
    "prog4_spell_name_table": PROG4_SPELL_NAME_TABLE,
    "prog5_menu_geometry": PROG5_MENU_GEOMETRY,
    "prog4_menu_geometry": PROG4_MENU_GEOMETRY,
}


def engine_overlays(disabled=None):
    """Merge the ENABLED engine byte-patch modules into {iso_path: [(off, bytes)]}.

    `disabled` defaults to patch_registry's effective disable set (config +
    LANG3_DISABLE env). With nothing disabled this is byte-identical to merging
    every ENGINE_MODULE_DICTS value.
    """
    disabled = disabled_modules() if disabled is None else set(disabled)
    merged: dict[str, list] = {}
    for name, module in ENGINE_MODULE_DICTS.items():
        if name in disabled:
            continue
        for path, edits in module.items():
            merged.setdefault(path, []).extend(edits)
    return merged

# JP disc location is contributor-specific. Set the LANG3_JP_DIR env
# var in your shell config to avoid passing --jp-iso every run.
_JP_DIR_ENV = 'LANG3_JP_DIR'


def main():
    import argparse, os
    parser = argparse.ArgumentParser(description='Build Langrisser III English Translation')
    parser.add_argument(
        '--jp-iso', type=Path, default=None,
        help='Path to Japanese disc directory (containing .cue and Track 01 .bin). '
             f'Falls back to ${_JP_DIR_ENV} env var if not given.',
    )
    parser.add_argument(
        '--lang', default=DEFAULT_LANG, choices=sorted(LANGUAGES.keys()),
        help=f'Translation language code (default: {DEFAULT_LANG}). Picks '
             f'scripts/<lang>/ as the source directory and shapes the output '
             f'filename. Add new entries to LANGUAGES in this file.',
    )
    args = parser.parse_args()
    lang_display = LANGUAGES[args.lang]
    SCRIPTS_DIR = SCRIPT_DIR / 'scripts' / args.lang
    # The image ships as a self-contained folder named after the .cue: e.g.
    #   build/Langrisser III (English v0.6+new-ui-patch)/
    #       Langrisser III (English v0.6+new-ui-patch).cue
    #       track01.bin ... track22.bin
    # The cue's FILE entries are siblings (relative), so the folder is movable
    # as a unit. assemble_cd_image() writes every track into output_cue.parent.
    cue_name = _resolve_canonical_cue_name(lang_display)
    output_dir = BUILD_DIR / Path(cue_name).stem
    output_cue = output_dir / cue_name

    # Resolve JP disc location: CLI flag → env var → error
    env_path = os.environ.get(_JP_DIR_ENV)
    jp_dir = args.jp_iso or (Path(env_path) if env_path else None)
    if jp_dir is None:
        print(f'ERROR: JP disc directory not configured.')
        print(f'  Either pass --jp-iso /path/to/disc/directory')
        print(f'  or set the {_JP_DIR_ENV} env var (e.g. in ~/.bashrc):')
        print(f'    export {_JP_DIR_ENV}="/path/to/Langrisser III (Japan)"')
        return 1
    jp_dir = Path(jp_dir)
    if not jp_dir.exists():
        print(f'ERROR: JP disc directory not found: {jp_dir}')
        return 1

    # Find Track 01 .bin (the data track)
    track01_candidates = list(jp_dir.glob('*rack*01*.bin')) + list(jp_dir.glob('*rack*1*.bin'))
    if not track01_candidates:
        track01_candidates = list(jp_dir.glob('*.bin'))
    jp_track01 = track01_candidates[0] if track01_candidates else None

    start_time = time.time()

    print('=' * 60)
    print('  Langrisser III - English Translation Build')
    print('  by Ralf Guth - https://github.com/ralfguth/langrisser3-english')
    print('=' * 60)
    print()

    # Validate inputs
    if not jp_track01 or not jp_track01.exists():
        print(f'ERROR: No Track 01 .bin found in: {jp_dir}')
        print(f'  Expected a .bin file like "Langrisser III (Japan) (Track 01).bin"')
        return 1

    if not SCRIPTS_DIR.exists():
        print(f'ERROR: No translation scripts found in {SCRIPTS_DIR}')
        return 1

    BUILD_DIR.mkdir(parents=True, exist_ok=True)

    # Feature toggle (tools/patch_registry.py): report and validate the disable
    # list before building, so a typo'd module name is loud, not silent.
    _disabled = disabled_modules()
    if _disabled:
        _unknown = validate_disabled(_disabled)
        if _unknown:
            print(f'ERROR: unknown module(s) in disable list: {", ".join(sorted(_unknown))}')
            print(f'       valid names: see tools/patch_registry.py ALL_MODULES')
            return 1
        print(f'  ⚠ modules DISABLED for this build: {", ".join(sorted(_disabled))}')

    # -- Step 1: Read Japanese ISO --
    print('[1/7] Reading Japanese ISO...')
    image = bytearray(jp_track01.read_bytes())
    print(f'  Track 01: {len(image):,} bytes ({len(image) // SECTOR_SIZE} sectors)')

    # -- Step 2: Extract key files --
    print('[2/7] Extracting game files...')
    file_index = build_file_index(image)

    font_entry = file_index.get('LANG/FONT.BIN')
    d00_entry = file_index.get('LANG/SCEN/D00.DAT')
    plot_entry = file_index.get('LANG/PLOT.DAT')
    fnt_sys_entry = file_index.get('LANG/FNT_SYS.BIN')

    if not font_entry or not d00_entry:
        print('ERROR: Could not find FONT.BIN or D00.DAT in ISO')
        return 1

    font_data = extract_file_data(image, font_entry.extent, font_entry.size)
    d00_data = extract_file_data(image, d00_entry.extent, d00_entry.size)
    print(f'  FONT.BIN: {len(font_data):,} bytes ({len(font_data) // 32} tiles)')
    print(f'  D00.DAT:  {len(d00_data):,} bytes')

    plot_data = None
    if plot_entry:
        plot_data = extract_file_data(image, plot_entry.extent, plot_entry.size)
        print(f'  PLOT.DAT: {len(plot_data):,} bytes')

    fnt_sys_jp_data = None
    if fnt_sys_entry:
        fnt_sys_jp_data = extract_file_data(image, fnt_sys_entry.extent, fnt_sys_entry.size)
        print(f'  FNT_SYS.BIN: {len(fnt_sys_jp_data):,} bytes')

    syswin_entry = file_index.get('LANG/BATTLE/SYSWIN.BIN')
    syswin_jp_data = None
    if syswin_entry:
        syswin_jp_data = extract_file_data(image, syswin_entry.extent, syswin_entry.size)

    # Save JP D00.DAT, PLOT.DAT, FNT_SYS.BIN, and SYSWIN.BIN to the cache/ dir
    # for consumption by tests (test_d00, test_plot, test_fnt_sys_roundtrip,
    # test_syswin_roundtrip, test_entry_counts, test_control_code_parity) and
    # audit tools (translation_audit, plot_audit, semantic_audit,
    # signature_compare, dump_jp_scripts). cache/ is gitignored and lives at
    # the project root — keeps build/ for release artifacts only.
    CACHE_DIR.mkdir(parents=True, exist_ok=True)
    (CACHE_DIR / 'd00_jp.dat').write_bytes(d00_data)
    if plot_data is not None:
        (CACHE_DIR / 'plot_jp.dat').write_bytes(plot_data)
    if fnt_sys_jp_data is not None:
        (CACHE_DIR / 'fnt_sys_jp.bin').write_bytes(fnt_sys_jp_data)
    if syswin_jp_data is not None:
        (CACHE_DIR / 'syswin_jp.bin').write_bytes(syswin_jp_data)

    # -- Step 3: Generate English font (toggleable: 'font') --
    print('[3/7] Generating English font...')
    if is_enabled('font'):
        new_font = generate_english_font(font_data)
        print(f'  English font: {len(new_font):,} bytes ({len(new_font) // 32} tiles)')
    else:
        new_font = font_data
        print('  [disabled] shipping JP FONT.BIN')

    # -- Step 4: Parse D00.DAT --
    print('[4/7] Parsing D00.DAT...')
    sections = parse_d00(d00_data)
    total_entries = sum(s.entry_count for s in sections)
    print(f'  {len(sections)} sections, {total_entries:,} entries total')

    # -- Step 5: Insert English translations (toggleable: 'scen_d00') --
    print('[5/7] Encoding English translations...')
    scen_enabled = is_enabled('scen_d00')
    new_text_areas = None
    if scen_enabled:
        new_text_areas, stats = insert_translations(
            sections, SCRIPTS_DIR, CHAR_TILE_MAP, _D00_BIGRAM, verbose=False
        )
        print(f'  Translated: {stats["translated"]} sections')
        print(f'  Skipped:    {stats["skipped"]} sections')
        if stats['entry_count_mismatches']:
            print(f'  Entry count adjustments: {len(stats["entry_count_mismatches"])}')
        if stats['errors']:
            for err in stats['errors']:
                print(f'  WARNING: {err}')
    else:
        print('  [disabled] shipping JP D00.DAT (no English dialogue)')

    # -- Step 6: Rebuild D00.DAT and patch ISO --
    print('[6/7] Rebuilding and patching ISO...')

    # Collect all files to patch. Same-size patches are applied in-place
    # via patch_file_in_iso. Files that grow are deferred to rebuild_iso_batch
    # which shifts subsequent sectors and updates all downstream dir records.
    grown_patches = []  # list of (iso_path, new_data) for files that grew

    # FONT.BIN: same size in production (1691 tiles). The font-growth spike
    # (LANG3_FONT_GROW) makes it larger -> defer to the sector-shift batch,
    # same as FNT_SYS/TITLE.DG2. See archive/docs/20260625_font_bin_grow_spike.md.
    if len(new_font) == font_entry.size:
        patch_file_in_iso(image, font_entry, new_font)
        print(f'  FONT.BIN patched in place')
    else:
        grown_patches.append(('LANG/FONT.BIN', new_font))
        print(f'  FONT.BIN regenerated: {font_entry.size:,} -> '
              f'{len(new_font):,} bytes (deferred grow)')

    # FNT_SYS.BIN: generated from scripts/en/fntsys{1..15}E.txt against JP
    # baseline. Replaced the 0.2 patch patches/fnt_sys.bin overlay in Phase 2 of
    # the disembark. Same-size today (Phase 2 baseline = JP-equivalent
    # content); future translation phases may grow it.
    if fnt_sys_jp_data and fnt_sys_entry and is_enabled('fntsys'):
        new_fnt_sys = encode_fntsys(fnt_sys_jp_data, SCRIPTS_DIR,
                                    bigram_override=_FNTSYS_OVERRIDE)
        if len(new_fnt_sys) == fnt_sys_entry.size:
            patch_file_in_iso(image, fnt_sys_entry, new_fnt_sys)
            print(f'  FNT_SYS.BIN regenerated: {len(new_fnt_sys):,} bytes (same size)')
        else:
            grown_patches.append(('LANG/FNT_SYS.BIN', new_fnt_sys))
            print(f'  FNT_SYS.BIN regenerated: {fnt_sys_entry.size:,} -> '
                  f'{len(new_fnt_sys):,} bytes (deferred grow)')

    # SYSWIN.BIN: battle-window strings (Orders/Move/Attack/Yes/No/Loading)
    # regenerated from scripts/en/syswinE.txt over the JP shell. Replaces the
    # 0.2 patch-derived SYSWIN_OVERLAY blob (Phase 6 disembark complete) — that blob
    # drew 'Loading.……', 'BeginBattle' and zenkaku Unit digits. Always
    # same-size: build_syswin splices into the fixed window frame.
    if syswin_jp_data is not None and syswin_entry and is_enabled('syswin'):
        new_syswin = encode_syswin(syswin_jp_data, SCRIPTS_DIR / 'syswinE.txt',
                                   bigram_override=_FNTSYS_OVERRIDE)
        patch_file_in_iso(image, syswin_entry, new_syswin)
        print(f'  SYSWIN.BIN regenerated from syswinE.txt '
              f'({len(new_syswin):,} bytes)')

    # Byte-overlays: owned patches on JP binaries (see tools/byte_overlays.py).
    # Each entry is (offset, bytes_chunk) — chunk written at offset.
    # Script-driven encoders in tools/prog_text_tools.py contribute additional
    # entries (currently the prog_3 magic-name table); they are applied AFTER
    # the static edits, so encoder writes win at any overlapping offset.
    # PROG_3 text tables (magic/skill names + skill pointer redirect), toggleable.
    encoded = prog_text_encoded_overlays() if is_enabled("prog3_text_tables") else {}
    # Our own engine byte-patches over JP — one module per patched concern, each
    # independently toggleable by name via patch_registry (see ENGINE_MODULE_DICTS).
    engine = engine_overlays()
    overlay_paths = list(BYTE_OVERLAYS.keys())
    for src in (encoded, engine):
        for p in src:
            if p not in overlay_paths:
                overlay_paths.append(p)
    overlay_applied = 0
    overlay_total_bytes = 0
    for iso_path in overlay_paths:
        entry = file_index.get(iso_path)
        if not entry:
            print(f'  WARNING: overlay target {iso_path} not in ISO')
            continue
        jp_bytes = bytearray(extract_file_data(image, entry.extent, entry.size))
        edits = (list(BYTE_OVERLAYS.get(iso_path, ()))
                 + list(encoded.get(iso_path, ()))
                 + list(engine.get(iso_path, ())))
        for off, chunk in edits:
            # Backward-compat: a stray int (old prog_6 format) → wrap as 1-byte chunk.
            if isinstance(chunk, int):
                chunk = bytes([chunk])
            jp_bytes[off:off + len(chunk)] = chunk
            overlay_total_bytes += len(chunk)
        patch_file_in_iso(image, entry, bytes(jp_bytes))
        overlay_applied += 1
    if overlay_applied:
        print(f'  Byte-overlays: {overlay_applied} files, '
              f'{overlay_total_bytes} bytes owned')

    # Legacy 0.2 patch menu/UI overlays (MENU_PATCHES). As of Phase 3a (2026-05-27)
    # this dict is empty — all 7 0.2 patch binaries are now disembarked via
    # encoders or BYTE_OVERLAYS. Loop kept for forward-compat in case future
    # work introduces a same-size binary patch (unlikely; prefer overlays).
    if MENU_PATCHES and PATCHES_DIR.exists():
        patch_same_size = 0
        patch_grown = 0
        legacy_debts = []
        for iso_path, patch_filename in MENU_PATCHES.items():
            patch_file = PATCHES_DIR / patch_filename
            iso_entry = file_index.get(iso_path)
            if not (patch_file.exists() and iso_entry):
                continue
            patch_data = patch_file.read_bytes()
            if len(patch_data) == iso_entry.size:
                patch_file_in_iso(image, iso_entry, patch_data)
                patch_same_size += 1
            else:
                grown_patches.append((iso_path, patch_data))
                patch_grown += 1
            legacy_debts.append(patch_filename)
        print(f'  Menu/UI patches: {patch_same_size} in-place, {patch_grown} deferred (grow)')
        if legacy_debts:
            print(f'  ⚠ 0.2 patch-debt: {len(legacy_debts)} binaries still 0.2 patch-derived '
                  f'({", ".join(legacy_debts)})')

    # Rebuild D00.DAT (may grow) — only when scen_d00 is enabled; otherwise the
    # JP D00.DAT already in `image` ships unchanged.
    if scen_enabled:
        new_d00 = rebuild_d00(sections, new_text_areas)
        print(f'  D00.DAT: {len(d00_data):,} -> {len(new_d00):,} bytes')
        grown_patches.append(('LANG/SCEN/D00.DAT', new_d00))

    # Rebuild PLOT.DAT from scripts/en/plotE.txt (battle prep screens).
    # Without this, the JP-encoded PLOT.DAT is read through the EN font
    # mapping → mojibake on every battle prep narration.
    plot_script = SCRIPTS_DIR / 'plotE.txt'
    if plot_entry and plot_script.exists() and is_enabled('plot'):
        # Sanity: JP PLOT.DAT must round-trip cleanly through our parser
        plot_round_trip(plot_data)
        new_plot = encode_plot_script(plot_script, CHAR_TILE_MAP, _D00_BIGRAM)
        print(f'  PLOT.DAT: {len(plot_data):,} -> {len(new_plot):,} bytes')
        if len(new_plot) == plot_entry.size:
            patch_file_in_iso(image, plot_entry, new_plot)
            print(f'    patched in place')
        else:
            grown_patches.append(('LANG/PLOT.DAT', new_plot))
    elif plot_entry and not is_enabled('plot'):
        print('  PLOT.DAT: [disabled] shipping JP version')
    elif plot_entry:
        print(f'  PLOT.DAT: scripts/en/plotE.txt missing - leaving JP version (mojibake!)')

    # Opening movie (LANG/LANG.CPK): inject the English-subtitled, upscaled CPK
    # if the prebuilt asset is present (see tools/movie_tools.py). It is larger
    # than the JP original (~19.5 -> ~21 MB), so it grows Track 1 and rides the
    # same sector-shift path as D00.DAT. The Saturn streams this off the disc, so
    # tools/movie_tools.py caps its bitrate under the 2x CD read speed.
    movie_entry = file_index.get('LANG/LANG.CPK')
    if movie_entry and is_enabled('movie'):
        if MOVIE_CPK.exists():
            new_movie = MOVIE_CPK.read_bytes()
            if new_movie[:4] != b'FILM':
                print(f'  ERROR: {MOVIE_CPK} is not a Sega FILM/CPK (bad magic) - skipping')
            else:
                grown_patches.append(('LANG/LANG.CPK', new_movie))
                print(f'  LANG.CPK (opening FMV): {movie_entry.size:,} -> '
                      f'{len(new_movie):,} bytes (English-subtitled)')
        else:
            print(f'  LANG.CPK: [no asset at {MOVIE_CPK}] shipping JP opening')
    elif movie_entry:
        print('  LANG.CPK: [disabled] shipping JP opening')

    # TITLE.DG2 — MANDATORY patch-author credit. This is intentionally NOT a
    # toggleable module: the credit is hardwired into every build. We tile the
    # credit from assets/title_credit/title_credit_indexed.png into res0 (the title
    # logo map res1 has empty footer rows) and write the map cells
    # (tools/title_dg2.py). If the title file or the credit asset is missing, or the
    # credit ends up empty, the build ABORTS — there is no path that ships a build
    # without the credit printed into the game binary.
    title_entry = file_index.get('LANG/TITLE.DG2')
    if not title_entry:
        raise RuntimeError('LANG/TITLE.DG2 not found in ISO — required for the '
                           'mandatory title-screen credit')
    if not TITLE_CREDIT_ASSET.exists():
        raise RuntimeError(
            f'mandatory title credit asset missing: {TITLE_CREDIT_ASSET} — the '
            'patch-author credit cannot be skipped; restore the asset to build')
    jp_title = extract_file_data(image, title_entry.extent, title_entry.size)
    new_title = title_dg2.apply_full_logo(jp_title, str(TITLE_CREDIT_ASSET))
    credit_cells = title_dg2.footer_cell_count(new_title)
    if credit_cells == 0:
        raise RuntimeError('title credit produced an empty footer — refusing to '
                           'build without the credit printed into TITLE.DG2')
    grown_patches.append(('LANG/TITLE.DG2', new_title))
    print(f'  TITLE.DG2 (MANDATORY credit): {title_entry.size:,} -> '
          f'{len(new_title):,} bytes, {credit_cells} footer cells embedded')

    # (The credit's grayscale palette ramp is written into TITLE.DG2's own
    # embedded palette by apply_footer_indexed — no separate palette file.)

    # Batch: apply all grown patches (D00.DAT, the movie, any grown MENU_PATCHES)
    # in ascending extent order. Shifts downstream sectors and updates dir records.
    image = rebuild_iso_batch(image, file_index, grown_patches)
    print(f'  ISO rebuilt: {len(image):,} bytes ({len(image) // SECTOR_SIZE} sectors)')

    # Write patched track 01 directly into the image folder.
    track01_path = output_dir / 'track01.bin'
    track01_path.parent.mkdir(parents=True, exist_ok=True)
    track01_path.write_bytes(image)
    print(f'  Track 01: {len(image):,} bytes')

    # -- Step 7: Assemble CD image --
    print('[7/7] Assembling CD image...')
    assemble_cd_image(track01_path, jp_dir, output_cue)

    tracks = list(output_dir.glob('track*.bin'))
    audio_tracks = len(tracks) - 1

    elapsed = time.time() - start_time

    print()
    print('=' * 60)
    print('  BUILD COMPLETE')
    print('=' * 60)
    print(f'  Folder:       {output_dir}')
    print(f'  Cue:          {output_cue.name}')
    print(f'  Track 01:     {track01_path.stat().st_size:,} bytes')
    print(f'  Audio tracks: {audio_tracks}')
    print(f'  Build time:   {elapsed:.1f}s')
    print()
    print('  To play:')
    print(f'    load {output_cue.name}')
    print()
    print('  Patch by Ralf Guth')
    print('  https://github.com/ralfguth/langrisser3-english')

    return 0


if __name__ == '__main__':
    raise SystemExit(main())
